plugins {
    id 'com.android.application'
}

android {
    namespace 'com.demo.mycarview'
    compileSdk 35

    defaultConfig {
        applicationId 'com.demo.mycarview'
        minSdk 26
        targetSdk 35
        versionCode 25
        versionName '0.7.2'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.car.app:app:1.7.0'
    implementation 'androidx.car.app:app-projected:1.7.0'
}
